-- 1: What is the total revenue generated by male vs female
SELECT gender, SUM(purchase_amount_usd) as revenue
FROM customer
GROUP BY gender;

-- 2:  which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount_usd >= (select AVG(purchase_amount_usd) from customer)

--3: Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS "AVG.Rating"
FROM customer 
GROUP BY item_purchased 
ORDER BY AVG(review_rating) DESC
limit 5; 

--4: Compare the average Purchase Amount between Standard and Express Shipping.
SELECT shipping_type, 
ROUND(AVG(purchase_amount_usd::numeric), 3) 
FROM customer
WHERE shipping_type IN ('Standard','Express') 
GROUP BY shipping_type

--5: Do subscribed customers spend more? Compare average spend and total between subcribers and non-subscribers 
SELECT subscription_status,
COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount_usd::numeric), 2) AS avg_spend,
ROUND(SUM(purchase_amount_usd::numeric),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;